### ISSUE TITLE
Create PLAIN TextFile programmatically

### ISSUE THREAD

**Issue by loretoparisi** [readbeyond/aeneas#232]
I want to load a `TextFile` programmatically

```python
task = Task()
textfile = TextFile()
for identifier, frag_text in [
    (u"f001", [u"first fragment"]),
    (u"f002", [u"second fragment"]),
    (u"f003", [u"third fragment"])
]:
    textfile.add_fragment(TextFragment(identifier, Language.ENG, frag_text, frag_text))
task.text_file = textfile
```

but in my case I do not have the fragments, just a plain text like

```text
First sentence of Paragraph One.
Second sentence of Paragraph One.

First sentence of Paragraph Two.

First sentence of Paragraph Three.
Second sentence of Paragraph Three.
Third sentence of Paragraph Three.
```
If I try like

```python
from aeneas.textfile import TextFile
from aeneas.textfile import TextFileFormat
from aeneas.language import Language

text = 'First sentence of Paragraph One.\nSecond sentence of Paragraph One.\n\nFirst sentence of Paragraph Two.'

textfile = TextFile(file_format=TextFileFormat.PLAIN)
for line in text.splitlines():
    textfile.add_fragment(TextFragment("", Language.ENG, line, line))
```

I get an error
```sh
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/ubuntu/.local/lib/python3.5/site-packages/aeneas/textfile.py", line 269, in __init__
    self.lines = lines
  File "/home/ubuntu/.local/lib/python3.5/site-packages/aeneas/textfile.py", line 327, in lines
    raise TypeError(u"lines is not an instance of list")
TypeError: lines is not an instance of list
```

while if I pass the arguments `lines` and `filtered_lines` as lists like

```python
for line in text.splitlines():
   tf.add_fragment(TextFragment("", Language.ENG, [line], [line]))
```

it creates a `TextFile` instance that seems to respect the structure:

```
>>> print(tf)
 First sentence of Paragraph One.
 Second sentence of Paragraph One.
 
 First sentence of Paragraph Two.
 First sentence of Paragraph One.
 Second sentence of Paragraph One.
```

Is that correct?

**Comment by pettarin** [comment]
@loretoparisi yes, that is correct, because each text fragment is a list of lines --- to account for e.g. subtitles, where you want to align the timings with the union of the two lines, but the two lines are separate entities. See the docs: https://www.readbeyond.it/aeneas/docs/textfile.html#aeneas.textfile.TextFragment

**Comment by loretoparisi** [comment]
@pettarin thank you, closing then!
