### ISSUE TITLE
ESPEAKNGTTSWrapper: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by bran112299** [readbeyond/aeneas#251]
```
[DEBU] 2020-05-28 23:37:57.770322 ESPEAKNGTTSWrapper: Calling TTS engine via C extension or subprocess
[DEBU] 2020-05-28 23:37:57.770322 ESPEAKNGTTSWrapper: C extension '' not recognized
[DEBU] 2020-05-28 23:37:57.771319 ESPEAKNGTTSWrapper: Running the pure Python code
[DEBU] 2020-05-28 23:37:57.771319 ESPEAKNGTTSWrapper: Synthesizing multiple via subprocess...
[DEBU] 2020-05-28 23:37:57.771319 ESPEAKNGTTSWrapper: Calling TTS engine using multiple generic function...
[DEBU] 2020-05-28 23:37:57.771319 ESPEAKNGTTSWrapper: Determining codec and sample rate...
[DEBU] 2020-05-28 23:37:57.771319 ESPEAKNGTTSWrapper: Reading codec and sample rate from OUTPUT_AUDIO_FORMAT
[DEBU] 2020-05-28 23:37:57.771319 ESPEAKNGTTSWrapper: Determining codec and sample rate... done
[DEBU] 2020-05-28 23:37:57.772316 ESPEAKNGTTSWrapper:   codec:       pcm_s16le
[DEBU] 2020-05-28 23:37:57.772316 ESPEAKNGTTSWrapper:   sample rate: 22050
[DEBU] 2020-05-28 23:37:57.772316 ESPEAKNGTTSWrapper: Examining fragment 0 (no cache)...
[DEBU] 2020-05-28 23:37:57.772316 ESPEAKNGTTSWrapper: Language to voice code: 'eng-GBR' => 'en-gb'
[DEBU] 2020-05-28 23:37:57.772316 ESPEAKNGTTSWrapper: Calling helper function
[DEBU] 2020-05-28 23:37:57.772316 ESPEAKNGTTSWrapper: Synthesizer helper called with output_file_path=None => creating temporary output file
[DEBU] 2020-05-28 23:37:57.773314 ESPEAKNGTTSWrapper: Temporary output file path is 'C:\Users\bran1\AppData\Local\Temp\tmpmx9y9ch9.wav'
[DEBU] 2020-05-28 23:37:57.773314 ESPEAKNGTTSWrapper: TTS engine reads text from stdin
[DEBU] 2020-05-28 23:37:57.773314 ESPEAKNGTTSWrapper: Creating arguments list...
[DEBU] 2020-05-28 23:37:57.773314 ESPEAKNGTTSWrapper: Creating arguments list... done
[DEBU] 2020-05-28 23:37:57.773314 ESPEAKNGTTSWrapper: Calling TTS engine...
[DEBU] 2020-05-28 23:37:57.774311 ESPEAKNGTTSWrapper: Calling with arguments '['E:\\testsyncaudipo\\EXAMPLE\\eSpeak NG', '-v', 'en-gb', '-w', 'C:\\Users\\bran1\\AppData\\Local\\Temp\\tmpmx9y9ch9.wav']'
[DEBU] 2020-05-28 23:37:57.774311 ESPEAKNGTTSWrapper: Calling with text 'OF all the faculties (except that which I shall soon mention), you will find not one which is capable of contemplating itself, and, consequently, not capable either of approving or disapproving.'
[WARN] 2020-05-28 23:37:57.774311 ESPEAKNGTTSWrapper: An unexpected error occurred while calling TTS engine via subprocess
[WARN] 2020-05-28 23:37:57.774311 ESPEAKNGTTSWrapper: [WinError 5] Access is denied
[CRIT] 2020-05-28 23:37:57.774311 ESPEAKNGTTSWrapper: An unexpected error occurred in helper_function
[CRIT] 2020-05-28 23:37:57.774311 ESPEAKNGTTSWrapper: An unexpected error occurred in loop_function
[DEBU] 2020-05-28 23:37:57.774311 ESPEAKNGTTSWrapper: Synthesizing multiple via subprocess... done
[CRIT] 2020-05-28 23:37:57.775308 ExecuteTask: STEP 3 (synthesize text) FAILURE
[CRIT] 2020-05-28 23:37:57.775308 ExecuteTask: Unexpected error while executing task
[CRIT] 2020-05-28 23:37:57.775308 ExecuteTask: Both the C extension and the pure Python code failed. (Wrong arguments? Input too big?)
Traceback (most recent call last):
  File "C:\Users\bran1\AppData\Local\Programs\Python\Python37\lib\site-packages\aeneas\executetask.py", line 212, in _execute_single_level_task
    leaf_level=True
  File "C:\Users\bran1\AppData\Local\Programs\Python\Python37\lib\site-packages\aeneas\executetask.py", line 386, in _execute_inner
    synt_handler, synt_path, synt_anchors, synt_format = self._synthesize(text_file)
  File "C:\Users\bran1\AppData\Local\Programs\Python\Python37\lib\site-packages\aeneas\executetask.py", line 538, in _synthesize
    result = self.synthesizer.synthesize(text_file, path)
  File "C:\Users\bran1\AppData\Local\Programs\Python\Python37\lib\site-packages\aeneas\synthesizer.py", line 214, in synthesize
    backwards=backwards
  File "C:\Users\bran1\AppData\Local\Programs\Python\Python37\lib\site-packages\aeneas\ttswrappers\basettswrapper.py", line 442, in synthesize_multiple
    rconf=self.rconf
  File "C:\Users\bran1\AppData\Local\Programs\Python\Python37\lib\site-packages\aeneas\globalfunctions.py", line 907, in run_c_extension_with_fallback
    raise RuntimeError(u"Both the C extension and the pure Python code failed. (Wrong arguments? Input too big?)")
RuntimeError: Both the C extension and the pure Python code failed. (Wrong arguments? Input too big?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bran1\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\bran1\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\bran1\Desktop\anus.py", line 34, in <module>
    ExecuteTask(task, rconf=rconf, logger=logger).execute()
  File "C:\Users\bran1\AppData\Local\Programs\Python\Python37\lib\site-packages\aeneas\executetask.py", line 182, in execute
    self._execute_single_level_task()
  File "C:\Users\bran1\AppData\Local\Programs\Python\Python37\lib\site-packages\aeneas\executetask.py", line 225, in _execute_single_level_task
    self._step_failure(exc)
  File "C:\Users\bran1\AppData\Local\Programs\Python\Python37\lib\site-packages\aeneas\executetask.py", line 129, in _step_failure
    self.log_exc(u"Unexpected error while executing task", exc, True, ExecuteTaskExecutionError)
  File "C:\Users\bran1\AppData\Local\Programs\Python\Python37\lib\site-packages\aeneas\logger.py", line 351, in log_exc
    raise raise_type(raise_message)
aeneas.executetask.ExecuteTaskExecutionError: Unexpected error while executing task : Both the C extension and the pure Python code failed. (Wrong arguments? Input too big?)
```

I'm not using cew, I'm on windows 10 and I'm using Python 3.7, espeak works fine but epseak-ng which was in my Program Files folder gave me access denied. I tried to run the script as an administrator and moving espeak ng but I have the same issue.

**Comment by readbeyond** [comment]
Closing as "won't fix".

As of today, Windows users might want to use the latest available installer from SIL ( https://github.com/sillsdev/aeneas-installer --- but note that the last build is from 2023, and I have not tested it) or just install aeneas in a Linux VM run by [WSL](https://learn.microsoft.com/en-us/windows/wsl/)

( @pettarin might consider supporting running aeneas natively on Windows in a future v2.0, although following the WSL route is definitely "simple enough" for the motivated perspective user to significantly decrease the priority of native Windows support. )

**Comment by readbeyond** [comment]
@bran112299 I saw that type of error ``[WinError 5] Access is denied`` on my company Windows workstation, due to antivirus/antimalware software blocking access to certain files e.g. in temporary directories. If that is also your case, you might want to try disabling such protections (temporarily), if you are allowed to, and see if aeneas work.
