### ISSUE TITLE
Aeneas and ConversionSyntax error

### ISSUE THREAD

**Issue by anonap31** [readbeyond/aeneas#282]
I'm trying to run a function that someone else wrote (and left no documentation). I'm running into an error with aeneas on Colab and my local machine though. I can't find existing issues on here that might be helpful; I've already checked for slashes in the string which might cause ConversionSyntax errors - there are none. Can somebody help me out?

This is the error message: 
`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aeneas/executetask.py", line 199, in _execute_single_level_task
    (head_length, process_length, tail_length) = self._compute_head_process_tail(real_wave_mfcc)
  File "/usr/local/lib/python3.7/dist-packages/aeneas/executetask.py", line 472, in _compute_head_process_tail
    head_length = self.task.configuration["i_a_head"]
  File "/usr/local/lib/python3.7/dist-packages/aeneas/configuration.py", line 140, in __getitem__
    return self._cast(key, self.data[key])
  File "/usr/local/lib/python3.7/dist-packages/aeneas/configuration.py", line 155, in _cast
    return self.types[key](value)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-11-cecc16de07ad>", line 23, in createFile
    ExecuteTask(task).execute()
  File "/usr/local/lib/python3.7/dist-packages/aeneas/executetask.py", line 182, in execute
    self._execute_single_level_task()
  File "/usr/local/lib/python3.7/dist-packages/aeneas/executetask.py", line 225, in _execute_single_level_task
    self._step_failure(exc)
  File "/usr/local/lib/python3.7/dist-packages/aeneas/executetask.py", line 129, in _step_failure
    self.log_exc(u"Unexpected error while executing task", exc, True, ExecuteTaskExecutionError)
  File "/usr/local/lib/python3.7/dist-packages/aeneas/logger.py", line 351, in log_exc
    raise raise_type(raise_message)
aeneas.executetask.ExecuteTaskExecutionError: Unexpected error while executing task : [<class 'decimal.ConversionSyntax'>]
---------------------------------------------------------------------------
InvalidOperation                          Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/aeneas/executetask.py in _execute_single_level_task(self)
    198             self._step_begin(u"compute head tail")
--> 199             (head_length, process_length, tail_length) = self._compute_head_process_tail(real_wave_mfcc)
    200             real_wave_mfcc.set_head_middle_tail(head_length, process_length, tail_length)

________________________________________
9 frames
________________________________________
/usr/local/lib/python3.7/dist-packages/aeneas/executetask.py in _compute_head_process_tail(self, audio_file_mfcc)
    471         """
--> 472         head_length = self.task.configuration["i_a_head"]
    473         process_length = self.task.configuration["i_a_process"]

/usr/local/lib/python3.7/dist-packages/aeneas/configuration.py in __getitem__(self, key)
    139         if key in self.data:
--> 140             return self._cast(key, self.data[key])
    141         else:

/usr/local/lib/python3.7/dist-packages/aeneas/configuration.py in _cast(self, key, value)
    154             else:
--> 155                 return self.types[key](value)
    156         return value

InvalidOperation: [<class 'decimal.ConversionSyntax'>]

During handling of the above exception, another exception occurred:

ExecuteTaskExecutionError                 Traceback (most recent call last)
<ipython-input-17-84b6ad1326c7> in <module>()
----> 1 createFile('214')

<ipython-input-11-cecc16de07ad> in createFile(id)
     66         logging.exception(
     67             'Something went wrong creating json for ' + id + '\n\n')
---> 68         raise e

<ipython-input-11-cecc16de07ad> in createFile(id)
     21 
     22         # process Task
---> 23         ExecuteTask(task).execute()
     24 
     25         # output sync map to file

/usr/local/lib/python3.7/dist-packages/aeneas/executetask.py in execute(self)
    180             self._execute_multi_level_task()
    181         else:
--> 182             self._execute_single_level_task()
    183         self.log(u"Executing task... done")
    184 

/usr/local/lib/python3.7/dist-packages/aeneas/executetask.py in _execute_single_level_task(self)
    223             self.log(u"Executing single level task... done")
    224         except Exception as exc:
--> 225             self._step_failure(exc)
    226 
    227     def _execute_multi_level_task(self):

/usr/local/lib/python3.7/dist-packages/aeneas/executetask.py in _step_failure(self, exc)
    127         self.log_crit(u"STEP %d (%s) FAILURE" % (self.step_index, self.step_label))
    128         self.step_index += 1
--> 129         self.log_exc(u"Unexpected error while executing task", exc, True, ExecuteTaskExecutionError)
    130 
    131     def _step_total(self):

/usr/local/lib/python3.7/dist-packages/aeneas/logger.py in log_exc(self, message, exc, critical, raise_type)
    349             if exc is not None:
    350                 raise_message = u"%s : %s" % (message, exc)
--> 351             raise raise_type(raise_message)
    352 
    353     def log(self, message):
`

**Comment by ozdefir** [comment]
Which options do you use in the command line? It looks like aeneas got
confused while parsing them. I would double-check the syntax, especially
the punctuation.

**Comment by anonap31** [comment]
> Which options do you use in the command line? It looks like aeneas got confused while parsing them. I would double-check the syntax, especially the punctuation.

What do you mean by options?

**Comment by ozdefir** [comment]
Options like "is_audio_file_head_length". That's what aeneas thinks causes the problem.

**Comment by readbeyond** [comment]
@anonap31 I edited your original issue description, since it was unreadable. Next time please use a code block (open and close with three back-tick characters) please.

**Comment by readbeyond** [comment]
@anonap31 the error generates when the task configuration parameter for the head length is retrieved:

```
head_length = self.task.configuration["i_a_head"]
```

How was that parameter set? Programmatically or through a CLI option or a configuration file? You might want to check that, probably its value contains a typo or a wrong decimal separator, which produces the parsing error.

**Comment by readbeyond** [comment]
Closing this issue, given it is 4+ years old and likely a usage error.
